feat(Soojung-Kim) : 브랜치 변경
shirohoo/Practice-Algorithm pull request #170
Opened 2021-04-12 03:36 UTC by hailey21

# :ballot_box_with_check:***Pull Request : 김수정 ***

- ***Name*** : 김수정
- ***Github*** : hailey.soojung@gmail.com
- ***Notion*** : hailey.soojung@gmail.com
- ***Slack*** : hailey.soojung@gmail.com
- ***Date*** : 2021-04-12

2021-04-17 14:38 UTC, shirohoo requested changes
잡폴더 세개 지우셔야되요

2021-04-19 08:02 UTC, hailey21 commented
> 잡폴더 세개 지우셔야되요
삭제했습니다. 감사합니다.

2021-04-23 13:38 UTC, hailey21 commented
회사에 신규서비스 배포하느라 이번주는 ㅠ 주중에 하나도 못했네요 
이거 리뷰 때를 놓치니까 머지는 안돼고 쌓이고 있는듯.. ㅠㅠ 
PR을 삭제하고 다시 날리는게 좋을까요?

2021-04-24 04:24 UTC, shirohoo approved these changes

2021-04-24 04:24 UTC, merged